name: Clean up Preview Environment

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  clean_preview:
    name: Clean up Preview Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_ORG_API_TOKEN }}
      FLY_REGION: sjc
      FLY_ORG: personal
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - uses: superfly/fly-pr-review-apps@1.5.0
        with:
          name: pr-${{ github.event.number }}-seating-chart-app
          config: fly.toml
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}-${{ github.head_ref }}
          api_key: ${{ secrets.NEON_API_KEY }}
